server:
  port: 7001
spring:
  application:
    name: cloud-eureka-server7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: #集群指向其它eureka 单机就是7001自己
      #集群指向其它eureka
      defaultZone: http://eureka7002.com:7002/eureka/
      #单机就是7001自己
#      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    # true:关闭自我保护机制，保证不可用服务被及时踢除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000 #让服务端每隔2秒扫描一次，是服务能尽快的剔除

