server:
  port: 8094
dubbo:
  scan:
    base-packages: com.newland.usercenter.service.impl
  protocol:
    name: dubbo
    port: -1
spring:
  application:
    name: user-service-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848