server:
  port: 9542

eureka:
  client:
    service-url:
      defaultZone: http://localhost:4001/eureka
    enabled: true
    fetch-registry: true
spring:
  application:
    name: config-client9542
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        service-id: cloud-config-center9541
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.66.11
    port: 5672
    username: leellun
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
