server:
  port: 9541

spring:
  application:
    name: cloud-config-center9541
  cloud:
    config:
      server:
        git:
          # ??
          uri: sdf
          search-paths: #????
            - springcloud-config
      label: master #????

  rabbitmq:
    host: 192.168.66.11
    port: 5672
    username: leellun
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:4001/eureka

##rabbitmq????,??bus???????
management:
  endpoints: #??bus???????
    web:
      exposure:
        include: 'bus-refresh''
