server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: school-server
          uri: lb://school-server
          predicates:
            - Path=/api/school/**
          filters:
            - RewritePath=/api/school/(?<segment>.*),/$\{segment}
        - id: education-server
          uri: lb://education-server
          predicates:
            - Path=/api/education/**
          filters:
            - RewritePath=/api/education/(?<segment>.*),/$\{segment}
        - id: education2-server
          uri: lb://education2-server
          predicates:
            - Path=/api/education2/**
          filters:
            - RewritePath=/api/education2/(?<segment>.*),/$\{segment}
        - id: uaa-server
          uri: lb://uaa-server
          predicates:
            - Path=/api/uaa/**
          filters:
            - RewritePath=/api/uaa/(?<segment>.*),/$\{segment}
  redis:
    # Redis默认情况下有16个分片(库)，这里配置具体使用的分片，默认是0
    database: 0
    # redis服务器地址（填写自己的服务器地址）
    host: localhost
    # redis端口（默认6379）
    port: 6379
    #redis连接超时等待,10秒
    timeout: PT10S
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active:  50
        # 连接池中的最大空闲连接 默认 8
        max-idle: 20
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认 -1，这里配置10s
        max-wait: PT10S