server:
  port: 9531

spring:
  application:
    name: cloud-service9531
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:4001/eureka
    fetch-registry: true
    register-with-eureka: true
