server:
  port: 10011
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/bank1?useUnicode=true
    username: leellun
    password: liulun666
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.66.11:9876
        bindings:
          input1:
            consumer:
              # 是否使用广播消费，默认为 false 使用集群消费
              broadcasting: false

logging:
  level:
    root: info
    org:
      springframework:
        web: info