server:
  port: 10012
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/bank2?useUnicode=true
    username: leellun
    password: liulun666
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.66.11:9876
      bindings:
        input:
          group: consumer_group_txmsg_bank2
          destination: topic_txmsg
          content-type: application/json # 默认 application/json
logging:
  level:
    root: info
    org:
      springframework:
        web: info