server:
  port: 8023

spring:
  application:
    name: cloud-zuul-feign
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:4001/eureka
    fetch-registry: true
    register-with-eureka: true
feign:
  hystrix:
    enabled: true
