server:
  port: 8093

dubbo:
  protocol:
    name: dubbo
    port: -1
spring:
  application:
    name: order-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848