server:
  port: 8093

dubbo:
  application:
    name: order-service-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://192.168.66.11:2181
  config-center:
    address: zookeeper://192.168.66.11:2181
  metadata-report:
    address: zookeeper://192.168.66.11:2181