server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: hello1 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:9531        #匹配后提供服务的路由地址
          uri: lb://cloud-service9531 #匹配后提供服务的路由地址
          predicates:
            - Path=/gw1/**         # 断言，路径相匹配的进行路由

        - id: hello2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:9532          #匹配后提供服务的路由地址
          uri: lb://cloud-service9532 #匹配后提供服务的路由地址
          predicates:
            - Path=/gw2/**         # 断言，路径相匹配的进行路由
            #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:4001/eureka
    fetch-registry: true
    register-with-eureka: true

